services:
    # PDF service builders
    app.custom_tcpdf:
        public: true
        class: App\Pdf\CustomTcpdf
        arguments:
            - '@app.smart_assets_helper'
            - '@translator.default'
            - AppBundle\Entity\Windfarm
    app.audit_pdf_builder:
        public: true
        class: App\Service\AuditPdfBuilderService
        arguments:
            - '@white_october.tcpdf'
            - '@liip_imagine.cache.manager'
            - '@vich_uploader.templating.helper.uploader_helper'
            - '@app.smart_assets_helper'
            - '@translator.default'
            - '@app.damage_repository'
            - '@app.damage_category_repository'
            - '@app.blade_damage_repository'
            - '@app.customer_repository'
            - '@app.audit_model_diagram_bridge'
            - '@app.windfarm_builder_bridge'
            - '@app.factory_windfarm_blades_damages_helper'
            - '@app.manager_observation'
    app.windfarm_audits_pdf_builder:
        public: true
        class: App\Service\WindfarmAuditsPdfBuilderService
        arguments:
            - '@white_october.tcpdf'
            - '@liip_imagine.cache.manager'
            - '@vich_uploader.templating.helper.uploader_helper'
            - '@app.smart_assets_helper'
            - '@translator.default'
            - '@app.damage_repository'
            - '@app.damage_category_repository'
            - '@app.blade_damage_repository'
            - '@app.customer_repository'
            - '@app.audit_model_diagram_bridge'
            - '@app.windfarm_builder_bridge'
            - '@app.factory_windfarm_blades_damages_helper'
            - '@app.manager_observation'
    app.audit_model_diagram_bridge:
        public: true
        class: App\Service\AuditModelDiagramBridgeService
    app.windfarm_builder_bridge:
        public: true
        class: App\Service\WindfarmBuilderBridgeService
        arguments:
            - '@translator.default'
    app.workorder_pdf_builder:
        public: true
        class: App\Service\WorkOrderPdfBuilderService
        arguments:
            - '@translator.default'
            - '@app.smart_assets_helper'
    app.presence_monitoring_pdf_builder:
        public: true
        class: App\Service\PresenceMonitoringPdfBuilderService
        arguments:
            - '@translator.default'
            - '@app.smart_assets_helper'
