stof_doctrine_extensions:
    default_locale: '%default_locale%'
    orm:
        default:
            timestampable:  true
            translatable:   true
            softdeleteable: false
            sluggable:      false
            sortable:       false
            tree:           false
