twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        admin_tag_version:        'v2.0.17'
        main_brand_title:         '%project_web_title%'
        google_analytics_enabled: '%google_analytics_enabled%'
        google_analytics_account: '%google_analytics_account%'
        google_maps_api_key:      '%google_maps_api_key%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'Admin/Form/action_button_from_template.html.twig'
        - 'Admin/Form/audit_diagram_type_form_template.html.twig'
        - 'OhGoogleMaps/google_maps_form_widget.html.twig'
