vich_uploader:
    db_driver: orm
    mappings:
        image:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/image
            upload_destination: '%kernel.project_dir%/public/uploads/images/image'
        user:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/user
            upload_destination: '%kernel.project_dir%/public/uploads/images/user'
        blade:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/blade
            upload_destination: '%kernel.project_dir%/public/uploads/images/blade'
        customer:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/customer
            upload_destination: '%kernel.project_dir%/public/uploads/images/customer'
        work_order_task_photo:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/work_order_task_photo
            upload_destination: '%kernel.project_dir%/public/uploads/images/work_order_task_photo'
