language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - SYMFONY_ENV=test
    - APP_ENV=test

matrix:
  fast_finish: true
  include:
    - php: 7.4

services:
  - redis
  - mysql

before_install:
  - composer self-update
  - cp env.travis .env
  - cp env.travis .env.test

install:
  - composer install
  - ./bin/phpunit install

script:
  # setting up
  - ./bin/console cache:clear --env=test
  - ./bin/console doctrine:databa:create --no-interaction --env=test
  - ./bin/console doctrine:schema:update --force --env=test
  - ./bin/console hautelook:fixtures:load --no-interaction --env=test
  # checking & validating
  - ./bin/console lint:yaml config --env=test
  - ./bin/console lint:twig templates --env=test
  - ./bin/console lint:xliff translations --env=test
  - ./bin/console security:check --env=test
  - ./bin/console doctrine:schema:validate --no-interaction --env=test
  # testing
  - ./bin/phpunit --no-coverage

branches:
  only:
    - master
