imports:
    - { resource: 'repositories.yaml' }
    - { resource: 'admins.yaml' }

parameters:
    default_locale:           '%env(resolve:DEFAULT_LOCALE)%'
    database_server_version:  '%env(resolve:DATABASE_SERVER_VERSION)%'
    project_web_title:        '%env(resolve:PROJECT_WEB_TITLE)%'
    google_analytics_enabled: '%env(resolve:GOOGLE_ANALYTICS_IS_ENABLED)%'
    google_analytics_account: '%env(resolve:GOOGLE_ANALYTICS_ACCOUNT)%'
    google_maps_api_key:      '%env(resolve:GOOGLE_MAPS_API_KEY)%'
    delivery_dev_address:     '%env(resolve:DEV_DELIVERY_ADDRESS)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $defaultLocale: '%default_locale%'
            $krb:           '%kernel.root_dir%'
    App\:
        resource: '../src/*'
        exclude:  '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags:     ['controller.service_arguments']
    app.auth_customer:
        class: App\Service\AuthCustomerService
        arguments:
            - "@security.authorization_checker"
            - "@security.token_storage"
