imports:
    - { resource: 'services/pdfs.yaml' }
    - { resource: 'services/repositories.yaml' }
    - { resource: 'services/admins.yaml' }

parameters:
    default_locale:           '%env(string:DEFAULT_LOCALE)%'
    database_server_version:  '%env(resolve:DATABASE_SERVER_VERSION)%'
    project_web_title:        '%env(string:PROJECT_WEB_TITLE)%'
    project_url_base:         '%env(string:PROJECT_BASE_URL)%'
    google_analytics_enabled: '%env(bool:GOOGLE_ANALYTICS_IS_ENABLED)%'
    google_analytics_account: '%env(string:GOOGLE_ANALYTICS_ACCOUNT)%'
    google_maps_api_key:      '%env(string:GOOGLE_MAPS_API_KEY)%'
    delivery_dev_address:     '%env(string:DEV_DELIVERY_ADDRESS)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $defaultLocale:    '%default_locale%'
            $project_url_base: '%project_url_base%'
            $krb:              '%kernel.root_dir%'
    App\:
        resource: '../src/*'
        exclude:  '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    App\Controller\:
        resource: '../src/Controller'
        tags:
            - 'controller.service_arguments'
    # Managers
    app.manager_observation:
        class: App\Manager\ObservationManager
        arguments:
            - '@app.blade_damage_repository'
    app.manager_customer_ajax_response:
        class: App\Manager\CustomerAjaxResponseManager
        arguments:
            - '@app.audit_repository'
    app.manager_work_order:
        class: App\Manager\WorkOrderManager
        arguments:
            - '@doctrine.orm.entity_manager'
    # Factories
    app.factory_windfarm_blades_damages_helper:
        class: App\Factory\WindmillBladesDamagesHelperFactory
        arguments:
            - '@app.damage_category_repository'
    app.smart_assets_helper:
        public: true
        class: App\Service\SmartAssetsHelperService
        arguments:
            - '@kernel'
            - '%project_url_base%'
    # Guardians
    app.auth_customer:
        public: true
        class: App\Service\AuthCustomerService
        arguments:
            - '@security.authorization_checker'
            - '@security.token_storage'
    snc_second_level_cache:
        class: '%snc_redis.doctrine_cache_predis.class%'
        arguments:
            - '@snc_redis.doctrine'
